/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "./public/index.html"
  ],
  theme: {
    extend: {
      colors: {
        tertiary: "#1c6938",
        "secondary-fixed-dim": "#f7be1d",
        primary: "#276a00",
        "on-secondary-fixed": "#251a00",
        "on-surface": "#191c1b",
        "error-container": "#ffdad6",
        "on-surface-variant": "#41493a",
        "secondary-fixed": "#ffdf9a",
        "primary-container": "#3e841b",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#8bd79b",
        "surface-container-low": "#f2f4f2",
        "on-primary-fixed": "#072100",
        "on-tertiary-fixed-variant": "#005226",
        "surface-container-highest": "#e1e3e1",
        background: "#f8faf8",
        "surface-bright": "#f8faf8",
        "inverse-surface": "#2e3130",
        "on-secondary-container": "#6d5200",
        "surface-container": "#eceeec",
        "tertiary-fixed": "#a6f4b5",
        "on-error": "#ffffff",
        "surface-dim": "#d8dad9",
        "on-secondary": "#ffffff",
        "surface-tint": "#286c00",
        "on-secondary-fixed-variant": "#5a4300",
        "on-tertiary-fixed": "#00210b",
        "inverse-on-surface": "#eff1ef",
        "on-tertiary-container": "#f6fff3",
        "on-error-container": "#93000a",
        "primary-fixed": "#a9f780",
        "inverse-primary": "#8eda67",
        "surface-container-lowest": "#ffffff",
        "on-background": "#191c1b",
        secondary: "#785a00",
        error: "#ba1a1a",
        "on-primary-container": "#f8ffee",
        "surface-container-high": "#e6e9e7",
        surface: "#f8faf8",
        "outline-variant": "#c0cab6",
        "secondary-container": "#fdc425",
        "primary-fixed-dim": "#8eda67",
        outline: "#717a69",
        "tertiary-container": "#39834e",
        "on-primary-fixed-variant": "#1c5200",
        "surface-variant": "#e1e3e1",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        unit: "8px",
        "container-max": "1280px",
        "margin-desktop": "64px",
        gutter: "24px",
      },
      fontFamily: {
        "label-md": ["IBM Plex Sans Arabic", "sans-serif"],
        "body-md": ["IBM Plex Sans Arabic", "sans-serif"],
        "headline-lg-mobile": ["IBM Plex Sans Arabic", "sans-serif"],
        "body-lg": ["IBM Plex Sans Arabic", "sans-serif"],
        "headline-md": ["IBM Plex Sans Arabic", "sans-serif"],
        "display-lg": ["IBM Plex Sans Arabic", "sans-serif"],
        "headline-lg": ["IBM Plex Sans Arabic", "sans-serif"],
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "60px", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};